apiVersion: v1
kind: Service
metadata:
  name: {{ include "wireguard.fullname" . }}
  labels:
    {{- include "wireguard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 51820
      targetPort: wireguard
      protocol: UDP
      name: wireguard
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "wireguard.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "wireguard.fullname" . }}-dashboard
  labels:
    {{- include "wireguard.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 51821
      targetPort: dashboard
      protocol: TCP
      name: dashboard
  selector:
    {{- include "wireguard.selectorLabels" . | nindent 4 }}